baseURL = 'https://pablo.codes/'
languageCode = 'de-ch'
title = 'Pablo Codes'
theme = 'pablo.codes'
sectionPagesMenu = 'main'

[menus]
  [[menus.main]]
    name = 'README.md'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'MAINTAINERS.md'
    pageRef = '/MAINTAINERS.md'
    weight = 20
  [[menus.main]]
    name = 'OPERATING_MODEL.md'
    pageRef = '/OPERATING_MODEL.md'
    weight = 20
